import React, { useState } from "react";

interface SourceWireframeModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const SourceWireframeModal: React.FC<SourceWireframeModalProps> = ({
  isOpen,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const wireframeSummary = `<!-- MockupFlow Ingestion Summary -->
- Model: Sreeram S R MBA Portfolio Wireframe
- Screens & Sections Ingested:
  1. Fixed Monogram Navigation Bar with Section Anchors
  2. Hero Viewport with Orbiting Strategic Node Hub (Marketing, Analytics, Customer, Operations, Supply Chain)
  3. Executive Profile & 3 Core Strategic Pillars
  4. Academic Foundation Chronological Timeline
  5. 11 Functional Business Capabilities (Searchable & Filterable)
  6. Selected Case Studies: Royal Enfield CSAT & Mylamparai Socio-Economic Study
  7. Industrial Immersion: Teejay Prabha Dairy Cold-Chain Pipeline (4 Stages)
  8. Professional Certifications: NPTEL Elite & SEBI/NISM Accredited
  9. Cross-Functional Integration 4-Quadrant Simulator
  10. Dark Quantitative Paradigm Telemetry Curve & Principles
  11. Dual Marquee Continuous Tickers
  12. Executive Advisory Contact & Curriculum Vitae Brief Generator`;

  const handleCopy = () => {
    navigator.clipboard.writeText(wireframeSummary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-in fade-in duration-150">
      <div className="bg-surface-container-lowest w-full max-w-2xl rounded-2xl p-6 sm:p-8 shadow-2xl border border-surface-container-high relative max-h-[85vh] overflow-y-auto">
        <button
          onClick={onClose}
          className="absolute top-5 right-5 w-8 h-8 rounded-full bg-surface-container hover:bg-surface-container-high text-on-surface flex items-center justify-center transition-colors cursor-pointer"
        >
          ✕
        </button>

        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-xl bg-secondary/15 text-secondary flex items-center justify-center">
            <span className="material-symbols-outlined text-[24px]">code</span>
          </div>
          <div>
            <span className="font-label-sm text-[11px] text-secondary uppercase tracking-widest font-bold">
              Wireframe Ingestion Pipeline
            </span>
            <h3 className="font-headline-md text-headline-md text-primary font-bold">
              Source Architecture &amp; Specifications
            </h3>
          </div>
        </div>

        <p className="text-xs text-on-surface-variant mb-4">
          Below is the architectural breakdown generated by MockupFlow from the
          original HTML wireframe:
        </p>

        <pre className="p-4 rounded-xl bg-[#0e1b32] text-white font-mono text-xs overflow-x-auto whitespace-pre leading-relaxed border border-white/10">
          {wireframeSummary}
        </pre>

        <div className="mt-6 pt-4 border-t border-surface-container flex justify-between items-center">
          <button
            onClick={handleCopy}
            className="px-4 py-2 bg-surface-container hover:bg-surface-container-high rounded-xl text-xs font-semibold text-primary transition-colors cursor-pointer flex items-center gap-1.5"
          >
            <span className="material-symbols-outlined text-[16px]">
              {copied ? "check" : "content_copy"}
            </span>
            <span>
              {copied ? "Copied to Clipboard" : "Copy Ingestion Summary"}
            </span>
          </button>

          <button
            onClick={onClose}
            className="px-5 py-2 bg-primary text-white hover:bg-secondary rounded-xl text-xs font-semibold transition-colors cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
